default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("RAILS_MYSQL_USER") %>
  password: <%= ENV.fetch("RAILS_MYSQL_PASSWORD") %>
  host: <%= ENV.fetch("RAILS_MYSQL_HOST") %>
  port: <%= ENV.fetch("RAILS_MYSQL_PORT") %>
  timeout: 5000

development:
  <<: *default
  database: cpup_development

test:
  <<: *default
  database: cpup_test

production:
  <<: *default
  database: cpup_production
