source "https://rubygems.org"

gem "bootsnap", require: false
gem "importmap-rails"
gem "jbuilder"
gem "mysql2", "~> 0.5"
gem "puma", ">= 5.0"
gem "rails", "~> 7.2.2", ">= 7.2.2.1"
gem "sidekiq", "~> 7.3"
gem 'simple_form', '~> 5.3', '>= 5.3.1'
gem "sprockets-rails"
gem "stimulus-rails"
gem "sass-rails", "~> 6.0"
gem "turbo-rails"
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "pry", "~> 0.15"
  gem "rubocop-rails-omakase", require: false
end

group :development do
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara", "~> 3.40"
  gem "factory_bot", "~> 6.5"
  gem "rspec", "~> 3.13"
  gem "rspec-rails", "~> 7.1"
  gem "selenium-webdriver", "~> 4.27"
end

gem "devise", "~> 4.9"
